### ISSUE TITLE
Black background in search bar

### ISSUE THREAD

**Issue by vpinheiro38** [igooralm192/ProjetoPOO#15]
### Tarefa **_#14_**
> Implement transition when the user click on the search bar, showing a black background.
>
Observações:
- Esta issue sempre pertencerá a um **_Project_**, mas não a uma **_Milestone_**.
- Onde há **_num_** coloque o número da issue global.

**Comment by igooralm192** [comment]
@vpinheiro38 Se não falta adicionar mais nada então feche a issue e solicite um pull request da **_appbar_** para a **_main_activity_**.
